name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.0
  - scipy=1.13
  - matplotlib=3.9
  - h5py=3.12
  - pandas
  - ipykernel
  - ipython
  - decorator=5.1
  - jupyterlab
